version: 2.1

orbs:
  blackduck: signavio/blackduck@1.10.0
  fortify: signavio/fortify@2.0.0

references:
  workspace_root: &workspace_root "/home/circleci/workspace"
  ubuntu_image: &ubuntu_image "ubuntu-2004:202107-02"

  # container_config: &container_config
  #   docker:
  #     - image: cimg/node:14.18

  # container_config_browser: &container_config_browser
  #   docker:
  #     - image: cimg/node:14.18-browsers

  # run_black_duck_scan: &run_black_duck_scan
  #   steps:
  #     - checkout:
  #         path: *workspace_root
  #     - run: npm install svg-intersections
  #     - blackduck/blackduck-detect:
  #         blackduck-project-group: SAP_Signavio_Process_Manager
  #         blackduck-project-name: svg-intersections
  #         blackduck-project-path: *workspace_root

executors:
  fortify:
    machine:
      image: *ubuntu_image
    resource_class: 2xlarge

jobs:

  black_duck_scan:
    docker:
      - image: cimg/node:14.18
    working_directory: *workspace_root
    steps:
      - checkout:
          path: *workspace_root
      - run: 
          name: 'Build'
          command: npm install svg-intersections
      - blackduck/blackduck-detect:
          blackduck-project-group: SAP_Signavio_Process_Manager
          blackduck-project-name: svg-intersections
          blackduck-project-path: *workspace_root

  fortify-translate-and-scan-upload:
    executor: fortify
    working_directory: *workspace_root
    steps:
      - checkout
      - fortify/setup
      - run:
          name: 'Fortify translate: svg-intersections'
          command: |
            set -x
            sourceanalyzer \
              -b svg-intersections \
              -verbose \
              $(find . -type d -path '*/lib' | paste -s -d ' ')

      - run:
          name: 'Fortify: scan'
          command: |
            sourceanalyzer \
              -b svg-intersections \
              -verbose \
              -scan \
              -f svg-intersections.fpr
      - store_artifacts:
          path: svg-intersections.fpr
      - run:
          name: 'Fortify: upload'
          command: |
            fortifyclient \
               -url "$FORTIFY_SSC" \
               -authtoken "$SSC_API_TOKEN" \
               uploadFPR \
               -file svg-intersections.fpr \
               -project signavio-svg-intersections \
               -version master

workflows:
  version: 2
  black-duck-scan:
    triggers:
      # - schedule:
      #     cron: '0 0 * * *'
      #     filters:
      #       branches:
      #         only: master
    jobs:
      - black_duck_scan:
          context: BlackDuck

  weekly-fortify-scan:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - fortify-translate-and-scan-upload:
          context:
            - fortify